<header class="navbar navbar-inverse navbar-fixed-top">
    <div class="container">
        <div class="navbar-header">
            <button class="navbar-toggle collapse">
                <span class="sr-only">Toggle Navigation</span>
                <span class="icon-bar"> </span>
                <span class="icon-bar"> </span>
                <span class="icon-bar"> </span>
            </button>
            <a class="navbar-brand" href="<?= $this->url('home'); ?>"><?= $applicationName; ?></a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
            <?= $this->navigation('Navigation')->menu()->setUlClass('nav navbar-nav')->setPartial('partial/nav-menu'); ?>
            <?= $this->navigation('Navigation.Header')->menu()->setUlClass('nav navbar-nav navbar-right'); ?>
            <?= $this->partial('partial/header-form'); ?>
        </div>
    </div>
</header>