<?php

/* @var $container Zend\Navigation\Navigation */
$container = $this->container;

/* @var $navigation \Zend\View\Helper\Navigation */
$navigation = $this->navigation();

?>

<ul class="<?= $navigation->menu()->getUlClass(); ?>">
    <?php /* @var $page \Zend\Navigation\Page\AbstractPage */ ?>
    <?php foreach ($container as $page) : ?>
        <?php /* Test if page is allowed */ ?>
        <?php if (!$navigation->accept($page)) continue; ?>

        <?php /* Page without children */ ?>
        <?php if (!$page->hasPages()) : ?>
            <li <?= $page->isActive() ? ' class="active"' : ''; ?>>
                <a href="<?= $page->getHref(); ?>"<?= ($page->getTarget() != "") ? ' target="'.$page->getTarget().'"' : ''; ?>>
                    <?php if ($page->get("icon") !== "") : ?>
                        <span class="<?= $page->get("icon"); ?>"></span>
                    <?php endif; ?>
                    <?= $this->escapeHtml($this->translate($page->getLabel(), $navigation->getTranslatorTextDomain())); ?>
                </a>
            </li>
        <?php /* Page with children */ ?>
        <?php else : ?>
            <?php
                $access = false;
                foreach ($page->getPages() as $child) {
                    if ($navigation->accept($child) && $child->get('separator') !== true) {
                        $access = true;
                    }
                }
            ?>
            <?php if ($access) : ?>
                <li class="dropdown<?= $page->isActive(true) ? ' active' : ''; ?>">
                    <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                        <?php if ($page->get("icon") !== "") : ?>
                            <span class="<?= $page->get("icon"); ?>"></span>
                        <?php endif; ?>
                        <?= $this->escapeHtml($this->translate($page->getLabel(), $navigation->getTranslatorTextDomain())); ?>
                        <b class="caret"></b>
                    </a>
                    <ul class="dropdown-menu"><?= $this->partial('partial/nav-submenu', array('pages' => $page->getPages())); ?></ul>
                </li>
            <?php endif; ?>
        <?php endif; ?>
    <?php endforeach; ?>
</ul>